import { Link } from "wouter";
import { SEOHead } from "@/components/seo-head";
import { QRGeneratorWidget } from "@/components/qr-generator-widget";

const webAppSchema = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "QR King — Free QR Code Generator",
  url: "https://qrking.replit.app/",
  description: "Free online QR code generator. Turn any URL into a scannable QR code in seconds. No signup required.",
  applicationCategory: "UtilitiesApplication",
  operatingSystem: "Any",
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
  potentialAction: {
    "@type": "Action",
    name: "Generate QR Code",
    target: "https://qrking.replit.app/"
  }
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    { "@type": "Question", name: "Is QR King completely free?", acceptedAnswer: { "@type": "Answer", text: "Yes. QR King is 100% free with no hidden charges. You can generate and download as many QR codes as you want." } },
    { "@type": "Question", name: "Do I need to create an account?", acceptedAnswer: { "@type": "Answer", text: "No account or sign-up is required. Open the page, paste your URL, and generate your QR code instantly." } },
    { "@type": "Question", name: "What format is the downloaded QR code?", acceptedAnswer: { "@type": "Answer", text: "QR codes are downloaded as PNG files at 512×512 pixels — high enough resolution for both digital use and print." } },
    { "@type": "Question", name: "Do the QR codes expire?", acceptedAnswer: { "@type": "Answer", text: "No. QR codes generated by QR King are static and never expire. They work as long as the destination URL is accessible." } },
    { "@type": "Question", name: "Can I use these QR codes commercially?", acceptedAnswer: { "@type": "Answer", text: "Yes. There are no usage restrictions. QR codes from QR King can be used for personal or commercial purposes." } }
  ]
};

const qrTypes = [
  { href: "/qr/url", icon: "🌐", title: "URL / Website", desc: "Link to any website or landing page" },
  { href: "/qr/wifi", icon: "📶", title: "Wi-Fi", desc: "Share Wi-Fi credentials without typing" },
  { href: "/qr/vcard", icon: "👤", title: "vCard / Contact", desc: "Share your contact details digitally" },
  { href: "/qr/text", icon: "📝", title: "Plain Text", desc: "Encode any message or plain text" },
  { href: "/qr/social", icon: "📱", title: "Social Media", desc: "Link to your social profiles" },
];

const faqs = [
  { q: "Is QR King completely free?", a: "Yes. QR King is 100% free with no hidden charges. You can generate and download as many QR codes as you want." },
  { q: "Do I need to create an account?", a: "No account or sign-up is required. Open the page, paste your URL, and generate your QR code instantly." },
  { q: "What format is the downloaded QR code?", a: "QR codes are downloaded as PNG files at 512×512 pixels — high enough resolution for both digital use and print." },
  { q: "Do the QR codes expire?", a: "No. QR codes generated by QR King are static and never expire. They work as long as the destination URL is accessible." },
  { q: "Can I use these QR codes commercially?", a: "Yes. There are no usage restrictions. QR codes from QR King can be used for personal or commercial purposes." },
];

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col" style={{ background: "linear-gradient(170deg, #eff6ff 0%, #f8faff 50%, #eef2ff 100%)" }}>
      <SEOHead
        title="Free QR Code Generator — Create Custom QR Codes Instantly | QR King"
        description="Generate free QR codes in seconds. Paste any URL, create a high-quality QR code, preview live, and download as PNG. No signup required. Instant, free, unlimited."
        canonical="/"
        schema={[webAppSchema, faqSchema]}
      />

      {/* Header */}
      <header className="py-4 px-6 border-b border-slate-100 bg-white/70 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: "linear-gradient(135deg, #2563eb 0%, #4f46e5 100%)" }}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
                <rect x="3" y="3" width="7" height="7" rx="1" fill="white"/>
                <rect x="14" y="3" width="7" height="7" rx="1" fill="white"/>
                <rect x="3" y="14" width="7" height="7" rx="1" fill="white"/>
                <rect x="5" y="5" width="3" height="3" rx="0.5" fill="#2563eb"/>
                <rect x="16" y="5" width="3" height="3" rx="0.5" fill="#2563eb"/>
                <rect x="5" y="16" width="3" height="3" rx="0.5" fill="#2563eb"/>
                <rect x="14" y="14" width="3" height="3" rx="0.5" fill="white"/>
                <rect x="18" y="14" width="3" height="3" rx="0.5" fill="white"/>
                <rect x="14" y="18" width="3" height="3" rx="0.5" fill="white"/>
                <rect x="18" y="18" width="3" height="3" rx="0.5" fill="white"/>
              </svg>
            </div>
            <span className="font-bold text-slate-800">QR King</span>
          </Link>
          <nav className="hidden md:flex items-center gap-5 text-sm text-slate-600">
            <Link href="/qr/url" className="hover:text-blue-600 transition-colors">URL QR</Link>
            <Link href="/qr/wifi" className="hover:text-blue-600 transition-colors">Wi-Fi QR</Link>
            <Link href="/qr/vcard" className="hover:text-blue-600 transition-colors">vCard QR</Link>
            <Link href="/blog" className="hover:text-blue-600 transition-colors">Blog</Link>
            <Link href="/about" className="hover:text-blue-600 transition-colors">About</Link>
            <Link href="/contact" className="hover:text-blue-600 transition-colors">Contact</Link>
          </nav>
          <span className="text-xs text-slate-400 hidden sm:block">Free · No sign-up · Instant</span>
        </div>
      </header>

      <main className="flex-1 flex flex-col items-center px-4 pt-10 pb-20">

        {/* Hero */}
        <div className="text-center max-w-2xl mb-8">
          <div className="inline-flex items-center gap-2 bg-blue-50 text-blue-700 text-xs font-semibold px-3 py-1.5 rounded-full mb-5 border border-blue-100">
            <span className="w-1.5 h-1.5 bg-blue-500 rounded-full inline-block"></span>
            100% Free — No Sign-up Required
          </div>
          <h1 className="text-4xl sm:text-5xl font-extrabold text-slate-900 tracking-tight mb-4 leading-tight">
            Free QR Code Generator —{" "}
            <span style={{ background: "linear-gradient(135deg, #2563eb 0%, #6366f1 100%)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>
              Create Custom QR Codes in Seconds
            </span>
          </h1>
          <p className="text-base sm:text-lg text-slate-500 leading-relaxed">
            The fastest free QR code maker online. Paste any URL, generate a high-quality QR code instantly, preview live, and download as a square PNG. No account needed.
          </p>
        </div>

        {/* Trust signals */}
        <div className="flex flex-wrap justify-center gap-3 mb-8">
          {[
            { icon: "✓", label: "100% Free" },
            { icon: "✓", label: "No Sign-up" },
            { icon: "✓", label: "Instant Generation" },
            { icon: "✓", label: "512×512 PNG Download" },
            { icon: "✓", label: "No Watermark" },
          ].map(t => (
            <span key={t.label} className="inline-flex items-center gap-1.5 bg-white text-slate-700 text-xs font-medium px-3 py-1.5 rounded-full border border-slate-200 shadow-sm">
              <span className="text-green-500 font-bold">{t.icon}</span>
              {t.label}
            </span>
          ))}
        </div>

        {/* Generator */}
        <QRGeneratorWidget />

        {/* QR Types navigation */}
        <section className="mt-14 max-w-2xl w-full" aria-labelledby="types-heading">
          <h2 id="types-heading" className="text-xl font-bold text-slate-800 text-center mb-2">QR Code Types</h2>
          <p className="text-sm text-slate-500 text-center mb-6">Create QR codes for different use cases — each with its own optimized guide.</p>
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
            {qrTypes.map(t => (
              <Link
                key={t.href}
                href={t.href}
                className="flex flex-col items-center gap-2 bg-white rounded-xl p-4 text-center border border-slate-100 hover:border-blue-200 hover:bg-blue-50 transition-all duration-200 group"
              >
                <span className="text-2xl">{t.icon}</span>
                <span className="text-xs font-semibold text-slate-700 group-hover:text-blue-700">{t.title}</span>
                <span className="text-xs text-slate-400 leading-tight hidden sm:block">{t.desc}</span>
              </Link>
            ))}
          </div>
        </section>

        {/* How to use */}
        <section className="mt-12 max-w-2xl w-full" aria-labelledby="howto-heading">
          <h2 id="howto-heading" className="text-xl font-bold text-slate-800 text-center mb-6">How to Create a Free QR Code</h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {[
              { step: "1", title: "Paste Your URL", desc: "Enter any website address into the input field — http or https, any length." },
              { step: "2", title: "Generate Instantly", desc: "Click Generate QR Code. Your QR code is created in milliseconds, live on screen." },
              { step: "3", title: "Download & Use", desc: "Click Download PNG to save a 512×512 high-resolution PNG. Print or share anywhere." },
            ].map(s => (
              <div key={s.step} className="bg-white rounded-xl p-5 text-center border border-slate-100 shadow-sm">
                <div className="w-10 h-10 rounded-full flex items-center justify-center text-white font-bold text-lg mx-auto mb-3" style={{ background: "linear-gradient(135deg, #2563eb, #4f46e5)" }}>
                  {s.step}
                </div>
                <h3 className="font-semibold text-slate-800 text-sm mb-1">{s.title}</h3>
                <p className="text-xs text-slate-500 leading-relaxed">{s.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Features */}
        <section className="mt-12 max-w-2xl w-full" aria-labelledby="features-heading">
          <h2 id="features-heading" className="text-xl font-bold text-slate-800 text-center mb-6">Why Use QR King?</h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {[
              { icon: "⚡", title: "Instant Generation", desc: "QR codes are generated client-side in milliseconds — no server wait." },
              { icon: "🖨️", title: "Print-Ready Quality", desc: "512×512 px with error correction level H — sharp at any print size." },
              { icon: "🔒", title: "Private & Secure", desc: "Your URLs are processed locally in your browser. Nothing is stored." },
              { icon: "📱", title: "Mobile Friendly", desc: "Works perfectly on phones and tablets for on-the-go QR creation." },
              { icon: "🆓", title: "Completely Free", desc: "No freemium tricks, no watermarks, no upsells — just free QR codes." },
              { icon: "♾️", title: "Unlimited Use", desc: "Generate as many QR codes as you need, as often as you need." },
            ].map(f => (
              <div key={f.title} className="bg-white rounded-xl p-5 border border-slate-100 shadow-sm">
                <div className="text-2xl mb-2">{f.icon}</div>
                <h3 className="font-semibold text-slate-800 text-sm mb-1">{f.title}</h3>
                <p className="text-xs text-slate-500 leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Use cases */}
        <section className="mt-12 max-w-2xl w-full" aria-labelledby="usecases-heading">
          <h2 id="usecases-heading" className="text-xl font-bold text-slate-800 text-center mb-6">QR Code Use Cases</h2>
          <div className="bg-white rounded-2xl p-6 border border-slate-100 shadow-sm">
            <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {[
                "Restaurant menus & ordering",
                "Business cards & networking",
                "Social media profile sharing",
                "Product packaging & labels",
                "Event tickets & check-in",
                "Wi-Fi password sharing",
                "App store download links",
                "Payment & checkout links",
                "Email marketing campaigns",
                "Real estate listings",
              ].map(u => (
                <li key={u} className="flex items-center gap-2 text-sm text-slate-600">
                  <span className="w-1.5 h-1.5 bg-blue-500 rounded-full flex-shrink-0"></span>
                  {u}
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* FAQ */}
        <section className="mt-12 max-w-2xl w-full" aria-labelledby="faq-heading">
          <h2 id="faq-heading" className="text-xl font-bold text-slate-800 text-center mb-6">Frequently Asked Questions</h2>
          <div className="space-y-3">
            {faqs.map((faq, i) => (
              <details key={i} className="bg-white rounded-xl border border-slate-100 shadow-sm group">
                <summary className="px-5 py-4 font-semibold text-sm text-slate-800 cursor-pointer list-none flex items-center justify-between hover:text-blue-700 transition-colors">
                  {faq.q}
                  <span className="text-slate-400 group-open:rotate-180 transition-transform text-lg">▾</span>
                </summary>
                <p className="px-5 pb-4 text-sm text-slate-600 leading-relaxed">{faq.a}</p>
              </details>
            ))}
          </div>
        </section>

        {/* Blog teaser */}
        <section className="mt-12 max-w-2xl w-full" aria-labelledby="blog-heading">
          <div className="flex items-center justify-between mb-4">
            <h2 id="blog-heading" className="text-xl font-bold text-slate-800">QR Code Resources</h2>
            <Link href="/blog" className="text-sm text-blue-600 hover:underline font-medium">View all →</Link>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {[
              { href: "/blog/what-is-qr-code", title: "What Is a QR Code and How Does It Work?", date: "Jun 1, 2025" },
              { href: "/blog/qr-codes-for-business", title: "How to Create QR Codes for Business", date: "Jun 5, 2025" },
              { href: "/blog/static-vs-dynamic-qr-code", title: "Static vs Dynamic QR Code — Which to Use?", date: "Jun 15, 2025" },
              { href: "/blog/qr-code-marketing-guide-2026", title: "QR Code Marketing Guide 2026", date: "Jun 10, 2025" },
            ].map(p => (
              <Link key={p.href} href={p.href} className="block bg-white rounded-xl p-4 border border-slate-100 shadow-sm hover:border-blue-200 hover:bg-blue-50 transition-all duration-200 group">
                <p className="text-xs text-slate-400 mb-1.5">{p.date}</p>
                <p className="text-sm font-semibold text-slate-800 group-hover:text-blue-700 leading-snug">{p.title}</p>
              </Link>
            ))}
          </div>
        </section>
      </main>

      <footer className="py-8 border-t border-slate-100 bg-white/60">
        <div className="max-w-5xl mx-auto px-6">
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <div className="w-6 h-6 rounded-md flex items-center justify-center" style={{ background: "linear-gradient(135deg, #2563eb 0%, #4f46e5 100%)" }}>
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none">
                  <rect x="3" y="3" width="7" height="7" rx="1" fill="white"/>
                  <rect x="14" y="3" width="7" height="7" rx="1" fill="white"/>
                  <rect x="3" y="14" width="7" height="7" rx="1" fill="white"/>
                </svg>
              </div>
              <span className="text-sm font-semibold text-slate-700">QR King</span>
            </div>
            <nav className="flex flex-wrap justify-center gap-4 text-xs text-slate-500">
              <Link href="/qr/url" className="hover:text-blue-600">URL QR Code</Link>
              <Link href="/qr/wifi" className="hover:text-blue-600">Wi-Fi QR Code</Link>
              <Link href="/qr/vcard" className="hover:text-blue-600">vCard QR Code</Link>
              <Link href="/qr/text" className="hover:text-blue-600">Text QR Code</Link>
              <Link href="/qr/social" className="hover:text-blue-600">Social QR Code</Link>
              <Link href="/blog" className="hover:text-blue-600">Blog</Link>
              <Link href="/about" className="hover:text-blue-600">About</Link>
              <Link href="/contact" className="hover:text-blue-600">Contact</Link>
              <Link href="/privacy" className="hover:text-blue-600">Privacy Policy</Link>
              <Link href="/terms" className="hover:text-blue-600">Terms of Service</Link>
            </nav>
            <p className="text-xs text-slate-400">© 2025 QR King · Free QR Code Generator</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
